# fly.toml app configuration file generated for codevmedia-n8n on 2025-10-18T15:47:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codevmedia-n8n'
primary_region = 'dfw'

[build]
  image = 'n8nio/n8n'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

  [mounts]
  source = "data"
  destination = "/home/node/.n8n"

  [[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
